version: '3.5'
services:
  svn-proxy:
    build: ./nginx
    image: svn-proxy:latest
    hostname: svn-proxy
    container_name: svn-proxy
    networks:
      - nuts
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/ssl:/etc/nginx/ssl
      - ./data/nginx-proxy.log/:/var/log/nginx/
    restart: always
    ports:
      - 8889:8889
networks:
  nuts:
    driver: bridge      